### ISSUE TITLE
Parallel Text generation: unsolved problem?

### ISSUE THREAD

**Issue by equwal** [Vuizur/awesome-language-learning#2]
Can't find an email for you so doing it here.

This is a company that sells just a couple dozen hand-edited parallel texts (by putting the translations between the lines, a clever solution)
https://interlinearbooks.com/

Parallel texts can be a great tool but they are annoying to make and scarce by nature. It makes the most to generate them on-the-fly when people want them for a specific text.

Here's an example
https://www.russianlessons.net/ebooks/show/1/1/1/both

This is a book I had when I started learning Russian, it really does it right by having stress marked and yofication:
https://www.amazon.com/Russian-Stories-Dual-Language-Book-English/dp/0486262448

There are some systems which provide machine-generated translations interlinearly, but the gold standard is to match up a human-made translation. I could imagine a system similar to "add-stress-to-epub" to generate these.

**Comment by Vuizur** [comment]
I agree that it definitely is a great way to teach languages. xxyzz has done a lot of amazing work in this direction, he develops his calibre extension [WordDumb](https://github.com/xxyzz/WordDumb). I think that this is the most promising project in this direction. It currently only doesn't work with stressed Russian epubs yet properly, it might be worth it to ask him to support it, or we need to implement the CSS workaround

**Comment by equwal** [comment]
Interesting, I'm interested in wordumb for sure.

I also mentioned you over here for adding macrons to latin
https://github.com/Alatius/latin-macronizer/issues/24
check it out if interested

His project has similar accuracy to this, I suggested making it support epubs. A better solution would be to separate out the epub generation into a seperate program (what do epubs have to do with marking stress in Russian? They are separate things) so that the epub generation can be used for any arbitrary language frobber.

**Comment by equwal** [comment]
> I agree that it definitely is a great way to teach languages. xxyzz has done a lot of amazing work in this direction, he develops his calibre extension [WordDumb](https://github.com/xxyzz/WordDumb). I think that this is the most promising project in this direction. It currently only doesn't work with stressed Russian epubs yet properly, it might be worth it to ask him to support it (Edit: I did now), or we need to implement the CSS workaround. But it's also not clear if Worddumb will even work with the suggested CSS workaround.

"supported languages [..]Русский[..]"

**Comment by Vuizur** [comment]
> His project has similar accuracy to this, I suggested making it support epubs. A better solution would be to separate out the epub generation into a seperate program (what do epubs have to do with marking stress in Russian? They are separate things) so that the epub generation can be used for any arbitrary language frobber.

You can edit my repo to support adding macrons to Latin texts. The most relevant line is [here](https://github.com/Vuizur/add-stress-to-epub/blob/master/russian_text_stresser/ebook_stresser.py#L52), you would only need to apply the linked program for Latin there.

Originally the stress setting of my program was pretty primitive, so the main innovation was that it worked for epubs. I just haven't changed the name.

> ["supported languages [..]Русский[..]"](https://github.com/xxyzz/WordDumb)

Yes, but the default settings only work for unstressed books. I added a note that you must disable POS if you want it to work with stressed texts, so you lose some functionality, but it still works OK.
